# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  sklib_config = debug

else ifeq ($(config),release)
  sklib_config = release

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := sklib

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

sklib:
ifneq (,$(sklib_config))
	@echo "==== Building sklib ($(sklib_config)) ===="
	@${MAKE} --no-print-directory -C . -f sklib.make config=$(sklib_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f sklib.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   sklib"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"